const bcrypt = require('bcrypt')
require('dotenv').config()

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex.raw('DELETE FROM "student"; ALTER SEQUENCE student_id_seq RESTART WITH 73;')
    .then(function () {
      var students = [ { id: 1,
        fullName: 'Amber Johnson',
        firstName: 'Amber',
        lastName: 'Johnson',
        email: 'amber.johnson.smile@gmail.com',
        code: 'T79H5TG8',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=T79H5TG8',
        studentSlackName: 'U79BZS9FW',
        githubUsername: 'amberjohnsonsmile',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 2,
        fullName: 'Benjamin Casalino',
        firstName: 'Benjamin',
        lastName: 'Casalino',
        email: 'bencasalino@gmail.com',
        code: '2S9ZXHDE',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=2S9ZXHDE',
        studentSlackName: 'U78DPH56U',
        githubUsername: 'bencasalino',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 3,
        fullName: 'BJ Collins',
        firstName: 'BJ',
        lastName: 'Collins',
        email: 'collinsbj@me.com',
        code: 'P8RZ5AQX',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=P8RZ5AQX',
        studentSlackName: 'U6FHY4QF7',
        githubUsername: 'collinsbj',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 4,
        fullName: 'Brandon Johnson',
        firstName: 'Brandon',
        lastName: 'Johnson',
        email: 'bmj1985@gmail.com',
        code: '6UHT8LHH',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=6UHT8LHH',
        studentSlackName: 'U7EH6FSKH',
        githubUsername: 'bmj1985',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 5,
        fullName: 'Brian Novak',
        firstName: 'Brian',
        lastName: 'Novak',
        email: 'brian.novak@me.com',
        code: 'UHKBUDXC',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=UHKBUDXC',
        studentSlackName: 'U79R2KFGU',
        githubUsername: 'briannovak',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 6,
        fullName: 'Bryan Long',
        firstName: 'Bryan',
        lastName: 'Long',
        email: 'bryanlong1@gmail.com',
        code: 'RHR3Z9DL',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=RHR3Z9DL',
        studentSlackName: 'U6FE1DB3L',
        githubUsername: 'BryanLong14',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 7,
        fullName: 'Carolyn Selheim-Miller',
        firstName: 'Carolyn',
        lastName: 'Selheim-Miller',
        email: 'carolyn.selheim@gmail.com',
        code: 'VGSEJK3R',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=VGSEJK3R',
        studentSlackName: 'U791E1X19',
        githubUsername: 'CarolynSM',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 8,
        fullName: 'Charles Ballew',
        firstName: 'Charles',
        lastName: 'Ballew',
        email: 'charleswballewjr@gmail.com',
        code: 'FB9R7VM4',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=FB9R7VM4',
        studentSlackName: 'U6M8S5R4M',
        githubUsername: 'cwbjr',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 9,
        fullName: 'Chas Fricke',
        firstName: 'Chas',
        lastName: 'Fricke',
        email: 'frickec@gmail.com',
        code: 'L7FU3MPM',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=L7FU3MPM',
        studentSlackName: 'U7G7Q7VTM',
        githubUsername: 'chasfricke',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 10,
        fullName: 'Daniel Beerman',
        firstName: 'Daniel',
        lastName: 'Beerman',
        email: 'daniel.beerman@galvanize.com',
        code: '3AL76JSL',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=3AL76JSL',
        studentSlackName: 'U2P5R3JCW',
        githubUsername: 'Lebeerman',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 11,
        fullName: 'Emily Pancake',
        firstName: 'Emily',
        lastName: 'Pancake',
        email: 'epancake24@gmail.com',
        code: 'FHSVTHGK',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=FHSVTHGK',
        studentSlackName: 'U6KBU0Z4L',
        githubUsername: 'epancake',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 12,
        fullName: 'Erin Cernich',
        firstName: 'Erin',
        lastName: 'Cernich',
        email: 'eacernich@gmail.com',
        code: 'DFBRSD65',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=DFBRSD65',
        studentSlackName: '',
        githubUsername: 'erino23',
        isActive: false,
        role: 'student',
        cohort: 'g70' },
      { id: 13,
        fullName: 'James Mann',
        firstName: 'James',
        lastName: 'Mann',
        email: 'saxmannjr@yahoo.com',
        code: 'L5FUPAUN',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=L5FUPAUN',
        studentSlackName: 'U7389CFT9',
        githubUsername: 'mrsaxmannjr',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 14,
        fullName: 'James Truitt',
        firstName: 'James',
        lastName: 'Truitt',
        email: 'tru@rockyagirl.com',
        code: '3KZVCTQ4',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=3KZVCTQ4',
        studentSlackName: 'U7HUEHED6',
        githubUsername: 'trurocks',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 15,
        fullName: 'Jay Farnsworth',
        firstName: 'Jay',
        lastName: 'Farnsworth',
        email: 'jcfarnz@gmail.com',
        code: 'TPDMQNEE',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=TPDMQNEE',
        studentSlackName: 'U7DULMU03',
        githubUsername: 'JayFarnsworth',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 16,
        fullName: 'Justin Bleile',
        firstName: 'Justin',
        lastName: 'Bleile',
        email: 'justinxbleile@gmail.com',
        code: '6LEBYCHX',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=6LEBYCHX',
        studentSlackName: '',
        githubUsername: '',
        isActive: false,
        role: 'student',
        cohort: 'g70' },
      { id: 17,
        fullName: 'Kevin Kingdon',
        firstName: 'Kevin',
        lastName: 'Kingdon',
        email: 'kmkingdon@gmail.com',
        code: 'SFK7WY97',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=SFK7WY97',
        studentSlackName: 'U7FPT9YQZ',
        githubUsername: 'kmkingdon',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 18,
        fullName: 'Kevin O\'Brien',
        firstName: 'Kevin',
        lastName: 'O\'Brien',
        email: 'kevin.eugene.obrien@gmail.com',
        code: '4D5RAAT2',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=4D5RAAT2',
        studentSlackName: 'U793Z6CCS',
        githubUsername: 'kevinEobrien',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 19,
        fullName: 'Kyle Weintraub',
        firstName: 'Kyle',
        lastName: 'Weintraub',
        email: 'weintraub.kyle@gmail.com',
        code: 'SFYEYWQY',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=SFYEYWQY',
        studentSlackName: 'U791HN927',
        githubUsername: 'TheMoonMoth',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 20,
        fullName: 'Malcolm Foster',
        firstName: 'Malcolm',
        lastName: 'Foster',
        email: 'malcolmfoster@gmail.com',
        code: 'NEVTH734',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=NEVTH734',
        studentSlackName: 'U7F75S495',
        githubUsername: 'mfoster1989',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 21,
        fullName: 'Matthew Meyer',
        firstName: 'Matthew',
        lastName: 'Meyer',
        email: 'matthew.meyer29@gmail.com',
        code: 'DHYZ57RD',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=DHYZ57RD',
        studentSlackName: 'U6K0V9P1B',
        githubUsername: 'mmeyer29',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 22,
        fullName: 'Michael Marlow',
        firstName: 'Michael',
        lastName: 'Marlow',
        email: 'michael.s.marlow@gmail.com',
        code: 'R9PVQD2F',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=R9PVQD2F',
        studentSlackName: 'U7KL169UL',
        githubUsername: 'Vision-X',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 23,
        fullName: 'Nicholas Solimine',
        firstName: 'Nicholas',
        lastName: 'Solimine',
        email: 'nick.solimine1@gmail.com',
        code: 'P7AJL462',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=P7AJL462',
        studentSlackName: 'U7C8RHSU9',
        githubUsername: '',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 24,
        fullName: 'Patrick Biffle',
        firstName: 'Patrick',
        lastName: 'Biffle',
        email: 'pbiffle@gmail.com',
        code: 'H2YFBKTK',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=H2YFBKTK',
        studentSlackName: 'U7A359004',
        githubUsername: 'Piglacquer',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 25,
        fullName: 'Paul Highum',
        firstName: 'Paul',
        lastName: 'Highum',
        email: 'phigh07@gmail.com',
        code: 'E83TKLQT',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=E83TKLQT',
        studentSlackName: 'U4JB3U8R1',
        githubUsername: 'paulhighum',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 26,
        fullName: 'Ross Prehn',
        firstName: 'Ross',
        lastName: 'Prehn',
        email: 'johnross.prehn@gmail.com',
        code: 'R8987LML',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=R8987LML',
        studentSlackName: 'U79TV28JX',
        githubUsername: 'rossprehn',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 27,
        fullName: 'Sarah Johnson',
        firstName: 'Sarah',
        lastName: 'Johnson',
        email: 'sarah@5280startupsolutions.co',
        code: '57P4S4CG',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=57P4S4CG',
        studentSlackName: 'U793BNV4Y',
        githubUsername: '',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 28,
        fullName: 'Tyler Mustard',
        firstName: 'Tyler',
        lastName: 'Mustard',
        email: 'tjm.0084@gmail.com',
        code: 'TS5DKMVC',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=TS5DKMVC',
        studentSlackName: 'U7E4SLLLC',
        githubUsername: 'TMustard',
        isActive: true,
        role: 'student',
        cohort: 'g70' },
      { id: 43,
        fullName: 'Job Smith',
        firstName: 'Job',
        lastName: 'Smith',
        email: 'jobsmith9@gmail.com',
        code: 'LL6JXO46',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=LL6JXO46',
        studentSlackName: 'U7XRM5XD2',
        githubUsername: '',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 44,
        fullName: 'John Salinas',
        firstName: 'John',
        lastName: 'Salinas',
        email: 'salinas3233@gmail.com',
        code: 'KIJY9V63',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=KIJY9V63',
        studentSlackName: 'U7WPJFVFB',
        githubUsername: 'jsalinas616',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 45,
        fullName: 'Sarah Battey',
        firstName: 'Sarah',
        lastName: 'Battey',
        email: 'sarahsbattey@gmail.com',
        code: 'OMTOGL4V',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=OMTOGL4V',
        studentSlackName: 'U6J2RFR1T',
        githubUsername: 'sarahbattey',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 46,
        fullName: 'Autumn Raine',
        firstName: 'Autumn',
        lastName: 'Raine',
        email: 'thetransvapor@gmail.com',
        code: 'T6YMLM2B',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=T6YMLM2B',
        studentSlackName: 'U7XFCBBAS',
        githubUsername: 'iNerdGirl',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 47,
        fullName: 'Pamela Yuhas',
        firstName: 'Pamela',
        lastName: 'Yuhas',
        email: 'pamelayuhas@gmail.com',
        code: 'EXQG51HP',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=EXQG51HP',
        studentSlackName: 'U7WGUCK35',
        githubUsername: 'pyuhas',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 48,
        fullName: 'Michael Schreier',
        firstName: 'Michael',
        lastName: 'Schreier',
        email: 'mjschreier1@gmail.com',
        code: 'PJGSLJW4',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=PJGSLJW4',
        studentSlackName: 'U7GFS723T',
        githubUsername: 'mjschreier',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 49,
        fullName: 'Clark Newell',
        firstName: 'Clark',
        lastName: 'Newell',
        email: 'williamcnewell@gmail.com',
        code: 'L6G0LC9Q',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=L6G0LC9Q',
        studentSlackName: 'U7K4WQW83',
        githubUsername: 'WCNewell',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 50,
        fullName: 'Jeff Burns',
        firstName: 'Jeff',
        lastName: 'Burns',
        email: '1jeffreyburns@gmail.com',
        code: 'E6M0EP17',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=E6M0EP17',
        studentSlackName: 'U6EQAF81W',
        githubUsername: '',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 51,
        fullName: 'Chance Scott-Burke',
        firstName: 'Chance',
        lastName: 'Scott-Burke',
        email: 'scottbur@gmail.com',
        code: 'NGR9LHA3',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=NGR9LHA3',
        studentSlackName: 'U7WHYNPRP',
        githubUsername: 'scottbur1323',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 52,
        fullName: 'Nikolaos Tsoukas',
        firstName: 'Nikolaos',
        lastName: 'Tsoukas',
        email: 'nick.tsoukas101@gmail.com',
        code: 'M97QZ1Q1',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=M97QZ1Q1',
        studentSlackName: 'U7X4J2124',
        githubUsername: 'Nick-tsoukas',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 53,
        fullName: 'Will Ferens',
        firstName: 'Will',
        lastName: 'Ferens',
        email: 'will.ferens@gmail.com',
        code: '5B5EEM1S',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=5B5EEM1S',
        studentSlackName: 'U7XHPLFKQ',
        githubUsername: 'will-ferens',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 54,
        fullName: 'Jasen Hill',
        firstName: 'Jasen',
        lastName: 'Hill',
        email: 'jasen@ready-builder.com',
        code: 'WLE6FSF2',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=WLE6FSF2',
        studentSlackName: 'U7GF75WP3',
        githubUsername: 'jasenmichael',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 55,
        fullName: 'Owen Black',
        firstName: 'Owen',
        lastName: 'Black',
        email: 'owenh.black@outlook.com',
        code: 'RB33E78L',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=RB33E78L',
        studentSlackName: 'U79A1A4AE',
        githubUsername: 'ohblack5280',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 56,
        fullName: 'Will Sheehan',
        firstName: 'Will',
        lastName: 'Sheehan',
        email: 'sheehan.will@gmail.com',
        code: 'RH5DDQ70',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=RH5DDQ70',
        studentSlackName: 'U7XFXHGQ6',
        githubUsername: '',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 57,
        fullName: 'Ryan Hackemer',
        firstName: 'Ryan',
        lastName: 'Hackemer',
        email: 'rhackemer@gmail.com',
        code: 'QEQU4CH8',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=QEQU4CH8',
        studentSlackName: 'U6L1N2PUM',
        githubUsername: '',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 58,
        fullName: 'David Aspesi',
        firstName: 'David',
        lastName: 'Aspesi',
        email: 'davidnaspesi@gmail.com',
        code: 'T8L72HT3',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=T8L72HT3',
        studentSlackName: 'U7X2UTVED',
        githubUsername: 'davidnaspesi',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 59,
        fullName: 'Jordan Smith',
        firstName: 'Jordan',
        lastName: 'Smith',
        email: 'jordansmith3326@yahoo.com',
        code: 'GWRGCOF0',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=GWRGCOF0',
        studentSlackName: 'U7HN5EX1B',
        githubUsername: 'JoSmith17',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 60,
        fullName: 'Seth Caparelli',
        firstName: 'Seth',
        lastName: 'Caparelli',
        email: 'sethcaparelli@gmail.com',
        code: '06R8137Q',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=06R8137Q',
        studentSlackName: 'U7WQD2D2R',
        githubUsername: 'SethCaparelli',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 61,
        fullName: 'Jacob Crane',
        firstName: 'Jacob',
        lastName: 'Crane',
        email: 'jcbcrn517@gmail.com',
        code: 'W52ZZ0NE',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=W52ZZ0NE',
        studentSlackName: 'U7XPP08S3',
        githubUsername: 'craneswalker',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 62,
        fullName: 'Michael Smith',
        firstName: 'Michael',
        lastName: 'Smith',
        email: 'milo0721@gmail.com',
        code: 'E94UQMND',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=E94UQMND',
        studentSlackName: 'U7X62CJUD',
        githubUsername: 'milo0721',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 63,
        fullName: 'Curtis Cooper',
        firstName: 'Curtis',
        lastName: 'Cooper',
        email: 'curtis_ac@hotmail.com',
        code: 'ENLGT0RV',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=ENLGT0RV',
        studentSlackName: 'U7WERR8BS',
        githubUsername: 'CC1589',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 64,
        fullName: 'Greg Paulos',
        firstName: 'Greg',
        lastName: 'Paulos',
        email: 'gregorypaulos@gmail.com',
        code: '99BL462N',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=99BL462N',
        studentSlackName: 'U7Y346B1C',
        githubUsername: 'gregpaulos',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 65,
        fullName: 'Austen Elswick',
        firstName: 'Austen',
        lastName: 'Elswick',
        email: 'austen.elswick@gmail.com',
        code: 'FP0MQ9AU',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=FP0MQ9AU',
        studentSlackName: 'U7XH6PPJA',
        githubUsername: 'Chaos9Theory',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 66,
        fullName: 'Roberto Santos',
        firstName: 'Roberto',
        lastName: 'Santos',
        email: 'roundwaves@gmail.com',
        code: '3CB9KOQ3',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=3CB9KOQ3',
        studentSlackName: 'U6FE1LUCA',
        githubUsername: '',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 67,
        fullName: 'Landon Folkers',
        firstName: 'Landon',
        lastName: 'Folkers',
        email: 'landonfolkers@yahoo.com',
        code: 'LRQK82DQ',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=LRQK82DQ',
        studentSlackName: 'U7WD5QUKB',
        githubUsername: 'landonfolkers',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 68,
        fullName: 'Zackary Moore',
        firstName: 'Zackary',
        lastName: 'Moore',
        email: 'bowchkabowwow@gmail.com',
        code: 'QUJIAIJI',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=QUJIAIJI',
        studentSlackName: 'U7X2UDWRH',
        githubUsername: 'chalked',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 69,
        fullName: 'Adam Basila',
        firstName: 'Adam',
        lastName: 'Basila',
        email: 'adamcbasila@gmail.com',
        code: '5RGAGIED',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=5RGAGIED',
        studentSlackName: 'U84B0DL3G',
        githubUsername: 'optimoosecrime',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 70,
        fullName: 'Benjamin Sullivan',
        firstName: 'Benjamin',
        lastName: 'Sullivan',
        email: 'bensully513@gmail.com',
        code: 'OL4YWZZ3',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=OL4YWZZ3',
        studentSlackName: 'U82TFDBAM',
        githubUsername: 'bensully17',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 71,
        fullName: 'Savannah Adams',
        firstName: 'Savannah',
        lastName: 'Adams',
        email: 'savannah.adams0@gmail.com',
        code: 'LVWI8MAG',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=LVWI8MAG',
        studentSlackName: 'U7X8YAT3L',
        githubUsername: 'cmission',
        isActive: true,
        role: 'student',
        cohort: 'g75' },
      { id: 72,
        fullName: 'Shaun Seidman',
        firstName: 'Shaun',
        lastName: 'Seidman',
        email: 'shaunseidman@gmail.com',
        code: '4W5EYDUJ',
        gradebook: 'https://g70-gradebook.firebaseapp.com/?student=4W5EYDUJ',
        studentSlackName: 'U7XFD73FY',
        githubUsername: 'shaunbseidman',
        isActive: true,
        role: 'student',
        cohort: 'g75' } ]
      return knex('student').insert(students);
    })
}
